self.__BUILD_MANIFEST = function(t, s, e, a, i, n, c, o, r, p, m, d, u, g, y, b, h, l, k, f, j, w) {
    return {
        __rewrites: {
            beforeFiles: [],
            afterFiles: [],
            fallback: []
        },
        "/": ["static/chunks/pages/index-177ac75f61e67dcb.js"],
        "/404": [t, a, i, u, "static/chunks/pages/404-a52b3cfcc5f342e9.js"],
        "/_error": ["static/chunks/pages/_error-6f7cf1371cb3cf32.js"],
        "/banner": [t, s, "static/chunks/pages/banner-af975386b9ff47cf.js"],
        "/bet-lt/[type_huay]": [t, s, e, "static/chunks/pages/bet-lt/[type_huay]-2fd2b0ce0e04753d.js"],
        "/bet-lt/[type_huay]/[sub_type_huay]": [t, s, e, "static/chunks/pages/bet-lt/[type_huay]/[sub_type_huay]-cb77993a4d2eee96.js"],
        "/bet-lt-conqueror/[type_huay]": [t, s, e, "static/chunks/pages/bet-lt-conqueror/[type_huay]-6ddfab352a6ecd34.js"],
        "/bet-lt-conqueror/[type_huay]/[sub_type_huay]": [t, s, e, "static/chunks/pages/bet-lt-conqueror/[type_huay]/[sub_type_huay]-f7c86a945de25d92.js"],
        "/betting-list": [t, s, "static/chunks/pages/betting-list-b47de7ec4595981b.js"],
        "/birthday-promotion/add": [t, s, "static/chunks/pages/birthday-promotion/add-4baa548c9c5637bb.js"],
        "/birthday-promotion/list": [t, s, "static/chunks/pages/birthday-promotion/list-00aee0a6c0ff50fa.js"],
        "/birthday-promotion/setting": [t, s, "static/chunks/pages/birthday-promotion/setting-f5e60be8277de867.js"],
        "/birthday-promotion/view": [t, s, "static/chunks/pages/birthday-promotion/view-68b1113640121975.js"],
        "/book-bank": [t, s, "static/chunks/pages/book-bank-df96038181d9c2e9.js"],
        "/book-bank/create": [t, s, "static/chunks/pages/book-bank/create-7aec5ab3599d59da.js"],
        "/book-bank/lock-bank-info/[id]": [t, s, "static/chunks/pages/book-bank/lock-bank-info/[id]-8394afeb8c0d57fd.js"],
        "/book-bank/[id]": [t, s, "static/chunks/pages/book-bank/[id]-aa2c1651eb233982.js"],
        "/book-bank-special/[bank_code]": [t, s, "static/chunks/pages/book-bank-special/[bank_code]-fd6daac5d6fed35e.js"],
        "/book-bank-special/[bank_code]/create": [t, s, "static/chunks/pages/book-bank-special/[bank_code]/create-bcb1f03ecc6d49b5.js"],
        "/book-bank-special/[bank_code]/[id]": [t, s, "static/chunks/pages/book-bank-special/[bank_code]/[id]-287b2a2f5dc1cc95.js"],
        "/casino-game": [t, s, "static/chunks/pages/casino-game-9582557ee15a4133.js"],
        "/change-password": [t, s, "static/chunks/pages/change-password-113fbd54c476807e.js"],
        "/commission/commission-game": [t, s, "static/chunks/pages/commission/commission-game-6681bd8ead9d1975.js"],
        "/commission/commission-month": [t, s, "static/chunks/pages/commission/commission-month-c8904aa8c546b1fe.js"],
        "/commission/commission-month-casino": [t, s, "static/chunks/pages/commission/commission-month-casino-55fc38a1c0c7b188.js"],
        "/commission/commission-weekly": [t, s, "static/chunks/pages/commission/commission-weekly-a664bf0ee3e67549.js"],
        "/commission/commission-weekly-casino": [t, s, "static/chunks/pages/commission/commission-weekly-casino-297503590affc367.js"],
        "/commission/setting-game-casino": [t, s, "static/chunks/pages/commission/setting-game-casino-903b7d387ac88a08.js"],
        "/commission-lottery/commission-lottery-month": [t, s, "static/chunks/pages/commission-lottery/commission-lottery-month-8274ee4358e93cc6.js"],
        "/commission-lottery/commission-lottery-year": [t, s, "static/chunks/pages/commission-lottery/commission-lottery-year-50250e4e267df9da.js"],
        "/contact": [p, t, s, a, n, i, c, o, r, m, d, "static/chunks/pages/contact-a2174a2ebf53deae.js"],
        "/contact-agent": [t, s, "static/chunks/pages/contact-agent-d462b58d76051b8c.js"],
        "/crypto/commission-crypto": [t, s, "static/chunks/pages/crypto/commission-crypto-d086b3104ed01db2.js"],
        "/crypto/commission-crypto-admin": [t, s, "static/chunks/pages/crypto/commission-crypto-admin-94f01bb4408472f8.js"],
        "/crypto/commission-crypto-master": [t, s, "static/chunks/pages/crypto/commission-crypto-master-8bcd7c394fe66e39.js"],
        "/crypto/setting-commission-crypto": [t, s, "static/chunks/pages/crypto/setting-commission-crypto-384a0a78ba3303fd.js"],
        "/crypto-wallet/own-wallet": [t, s, "static/chunks/pages/crypto-wallet/own-wallet-f3d02452d823380a.js"],
        "/crypto-wallet/own-wallet/wallet-crypto-trx": [t, s, "static/chunks/pages/crypto-wallet/own-wallet/wallet-crypto-trx-598bd44e43527722.js"],
        "/crypto-wallet/settlement-wallet-crypto": [t, s, "static/chunks/pages/crypto-wallet/settlement-wallet-crypto-1d3f950bd463ec27.js"],
        "/dashboard": [t, s, "static/chunks/pages/dashboard-2f0362b6ac41d6d4.js"],
        "/dashboard-game": [t, s, "static/chunks/pages/dashboard-game-de12474abe8597e9.js"],
        "/dashboard-system": [t, s, "static/chunks/pages/dashboard-system-f8de154799e959b1.js"],
        "/deposit-withdraw/all": [t, s, m, u, "static/chunks/pages/deposit-withdraw/all-5223a772fe815fe2.js"],
        "/deposit-withdraw/pending": [p, t, s, a, n, i, c, o, r, m, u, d, "static/chunks/pages/deposit-withdraw/pending-8de669caf93e7e5f.js"],
        "/direct-deposit-withdraw": [t, s, "static/chunks/pages/direct-deposit-withdraw-81d6ae804f91ac63.js"],
        "/home": [t, s, "static/chunks/pages/home-19b05ba33e26ada8.js"],
        "/login": [t, s, "static/chunks/pages/login-7c25dc913aaf1893.js"],
        "/lotto-huay/[type_huay]": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]-083e3c19ca753d4f.js"],
        "/lotto-huay/[type_huay]/bet-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/bet-setting-b913f17240d40abd.js"],
        "/lotto-huay/[type_huay]/dashboard": [t, s, "static/chunks/pages/lotto-huay/[type_huay]/dashboard-06e3fcdb325ab36b.js"],
        "/lotto-huay/[type_huay]/enable-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/enable-setting-9dc1a524c89eb2fe.js"],
        "/lotto-huay/[type_huay]/payment-rate-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/payment-rate-setting-c710078c97082310.js"],
        "/lotto-huay/[type_huay]/price-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/price-setting-c1f8a9c6e7fb43ff.js"],
        "/lotto-huay/[type_huay]/schedule-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/schedule-setting-69a8464514be2ed8.js"],
        "/lotto-huay/[type_huay]/thrust-round": [t, s, "static/chunks/pages/lotto-huay/[type_huay]/thrust-round-ee334724eb3fdb7c.js"],
        "/lotto-huay/[type_huay]/[sub_type_huay]": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/[sub_type_huay]-c3b37a4de2c7ad51.js"],
        "/lotto-huay/[type_huay]/[sub_type_huay]/bet-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/[sub_type_huay]/bet-setting-d5eca5ea725070c4.js"],
        "/lotto-huay/[type_huay]/[sub_type_huay]/dashboard": [t, s, "static/chunks/pages/lotto-huay/[type_huay]/[sub_type_huay]/dashboard-03a3ea17da7d57d0.js"],
        "/lotto-huay/[type_huay]/[sub_type_huay]/enable-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/[sub_type_huay]/enable-setting-19dd34bedac29f23.js"],
        "/lotto-huay/[type_huay]/[sub_type_huay]/payment-rate-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/[sub_type_huay]/payment-rate-setting-c841762132a84072.js"],
        "/lotto-huay/[type_huay]/[sub_type_huay]/schedule-setting": [t, s, e, "static/chunks/pages/lotto-huay/[type_huay]/[sub_type_huay]/schedule-setting-a34c0c61cdda8e72.js"],
        "/lotto-huay/[type_huay]/[sub_type_huay]/thrust-round": [t, s, "static/chunks/pages/lotto-huay/[type_huay]/[sub_type_huay]/thrust-round-ddeadf2c2a1812f2.js"],
        "/lucky-draw-banner": [t, s, "static/chunks/pages/lucky-draw-banner-bfc2523ec361eb9c.js"],
        "/lucky-draw-join-round": [t, s, "static/chunks/pages/lucky-draw-join-round-861e70fab5d714c0.js"],
        "/lucky-draw-level": [t, s, "static/chunks/pages/lucky-draw-level-c83ad59f3d96c6d3.js"],
        "/lucky-draw-level/setting": [t, s, "static/chunks/pages/lucky-draw-level/setting-e46f7291704bb56e.js"],
        "/lucky-draw-prizes": [t, s, "static/chunks/pages/lucky-draw-prizes-ad6f5f814145047e.js"],
        "/lucky-draw-prizes/detail/[id]": [t, s, "static/chunks/pages/lucky-draw-prizes/detail/[id]-95653a0ad9587f2f.js"],
        "/lucky-draw-setting-round": [t, s, "static/chunks/pages/lucky-draw-setting-round-4362ac62442e0500.js"],
        "/lucky-draw-setting-round/invite": [t, s, "static/chunks/pages/lucky-draw-setting-round/invite-d974bbbcd7b4e5ef.js"],
        "/lucky-draw-setting-round/setting": [t, s, "static/chunks/pages/lucky-draw-setting-round/setting-cde2ee6398201283.js"],
        "/lucky-draw-setting-round/setting-reward/[id]": [t, s, "static/chunks/pages/lucky-draw-setting-round/setting-reward/[id]-98c738d441b6ac06.js"],
        "/member": [p, t, s, a, n, i, c, o, r, m, d, "static/chunks/pages/member-8b527bbcc72e4f08.js"],
        "/member/bet/[id]": [t, s, "static/chunks/pages/member/bet/[id]-35d8d95e943e0c9e.js"],
        "/member/book-bank/[id]": [t, s, "static/chunks/pages/member/book-bank/[id]-d58dbab8eacb2e3a.js"],
        "/member/create": [t, s, "static/chunks/pages/member/create-075e99afa2624e95.js"],
        "/member/credit/[id]": [t, s, "static/chunks/pages/member/credit/[id]-decf1ef65a9ce0a4.js"],
        "/member/huay-transaction/[id]": [t, s, "static/chunks/pages/member/huay-transaction/[id]-993314d7525aa3f5.js"],
        "/member/log-history/[id]": [t, s, "static/chunks/pages/member/log-history/[id]-195a8ee71cb76443.js"],
        "/member/lucky-draw/[id]": [t, s, "static/chunks/pages/member/lucky-draw/[id]-5ab11e9cfd5c2e2b.js"],
        "/member/member-info/[id]": [t, s, "static/chunks/pages/member/member-info/[id]-c614d8fb2d8a3f15.js"],
        "/member/[id]": [t, s, "static/chunks/pages/member/[id]-1f96f3da8e821e53.js"],
        "/message-in": [p, t, s, a, n, i, c, o, r, m, d, "static/chunks/pages/message-in-aa8147facfdd3b6f.js"],
        "/message-out": [t, s, "static/chunks/pages/message-out-612872a842727923.js"],
        "/mini-games-hilo": [t, s, "static/chunks/pages/mini-games-hilo-201402c7221fefe0.js"],
        "/mini-games-huakoi": [t, s, "static/chunks/pages/mini-games-huakoi-dd356e4daaebc5b1.js"],
        "/mini-games-paoyingchub": [t, s, "static/chunks/pages/mini-games-paoyingchub-99e127520f634351.js"],
        "/mini-games-setting/[mini_game]": [p, t, s, "static/chunks/pages/mini-games-setting/[mini_game]-f4182618d48bc7ff.js"],
        "/monitoring": [t, s, "static/chunks/pages/monitoring-a9b00bba89a27a53.js"],
        "/monitoring/create": [t, s, "static/chunks/pages/monitoring/create-b7b67fe62ef69cd4.js"],
        "/monitoring/[id]": [t, s, "static/chunks/pages/monitoring/[id]-93c985ca6572d8d6.js"],
        "/new-member-promotion/list-new-member": [t, s, "static/chunks/pages/new-member-promotion/list-new-member-3554f35d99500dfc.js"],
        "/new-member-promotion/setting-new-member": [t, s, "static/chunks/pages/new-member-promotion/setting-new-member-3525f58e876dea4f.js"],
        "/promotion": [t, s, "static/chunks/pages/promotion-5acb1b7e306dc3eb.js"],
        "/promotion/create": [t, s, "static/chunks/pages/promotion/create-6190dbe824cfea28.js"],
        "/promotion/[id]": [t, s, "static/chunks/pages/promotion/[id]-6b7a29bf4d55dbcc.js"],
        "/promotion-direct-deposit/report": [t, s, "static/chunks/pages/promotion-direct-deposit/report-083f79f5d4c2c726.js"],
        "/promotion-direct-deposit/summary": [t, s, "static/chunks/pages/promotion-direct-deposit/summary-36ec70a6f454abda.js"],
        "/promotion-topup-direct-deposit/report": [t, s, "static/chunks/pages/promotion-topup-direct-deposit/report-35c12d434b791fc3.js"],
        "/promotion-topup-direct-deposit/summary": [t, s, "static/chunks/pages/promotion-topup-direct-deposit/summary-175d58575f663042.js"],
        "/promotion-user-list": [t, s, "static/chunks/pages/promotion-user-list-5f59f07d54560b00.js"],
        "/promotion-user-list/create": [t, s, "static/chunks/pages/promotion-user-list/create-dd7b1d5a5ac4f0ac.js"],
        "/promotion-user-list/update/[id]": [t, s, "static/chunks/pages/promotion-user-list/update/[id]-bee641d2e93ea2e7.js"],
        "/promotion-user-list/view/[id]": [t, s, "static/chunks/pages/promotion-user-list/view/[id]-00d94ecf4d76d3d8.js"],
        "/public-relations-announcement": [t, s, "static/chunks/pages/public-relations-announcement-fcbfcc6ce96d1c84.js"],
        "/public-relations-announcement/form": [t, s, "static/chunks/pages/public-relations-announcement/form-ae49f5926ec36712.js"],
        "/public-relations-announcement/[id]": [t, s, "static/chunks/pages/public-relations-announcement/[id]-73a1c7a77a2a4c4c.js"],
        "/public-relations-marquee": [t, s, "static/chunks/pages/public-relations-marquee-1159ae757f537cf9.js"],
        "/public-relations-news-popup": [t, s, "static/chunks/pages/public-relations-news-popup-ccb452d91918505c.js"],
        "/public-relations-news-popup/create": [t, s, "static/chunks/pages/public-relations-news-popup/create-42aec351800b901d.js"],
        "/public-relations-news-popup/[id]": [t, s, "static/chunks/pages/public-relations-news-popup/[id]-aab2f59b12e8f566.js"],
        "/public-relations-news-popup-casino": [t, s, "static/chunks/pages/public-relations-news-popup-casino-8a6140f76c8956fd.js"],
        "/public-relations-news-popup-casino/create": [t, s, "static/chunks/pages/public-relations-news-popup-casino/create-af3497d2f9ceaf15.js"],
        "/public-relations-news-popup-casino/[id]": [t, s, "static/chunks/pages/public-relations-news-popup-casino/[id]-8ad799cffe0ec847.js"],
        "/report-account-summary/calendar": [t, s, "static/chunks/pages/report-account-summary/calendar-2e597f5bd92d2228.js"],
        "/report-account-summary/retrospect": [t, s, "static/chunks/pages/report-account-summary/retrospect-9d779e29dce9099b.js"],
        "/report-account-summary/today": [t, s, "static/chunks/pages/report-account-summary/today-06d05e2d9bfdd774.js"],
        "/report-balance-bof": [t, s, "static/chunks/pages/report-balance-bof-f31a04b47d20460d.js"],
        "/report-credit-transaction/credit-transaction-agent": [t, s, "static/chunks/pages/report-credit-transaction/credit-transaction-agent-589f34313bcb190c.js"],
        "/report-credit-transaction/credit-transaction-agent-by-master": [t, s, "static/chunks/pages/report-credit-transaction/credit-transaction-agent-by-master-6b6fa60f4c63fffd.js"],
        "/report-credit-transaction/credit-transaction-all": [t, s, "static/chunks/pages/report-credit-transaction/credit-transaction-all-0b5cb44596ae9a10.js"],
        "/report-credit-transaction/credit-transaction-master": [t, s, "static/chunks/pages/report-credit-transaction/credit-transaction-master-fc907a0316a890ee.js"],
        "/report-credit-transaction/credit-transaction-member": [t, s, "static/chunks/pages/report-credit-transaction/credit-transaction-member-cfe4acca0b2fa3b2.js"],
        "/report-daily/daily-all": [t, s, "static/chunks/pages/report-daily/daily-all-5a7b36f62355f637.js"],
        "/report-daily/daily-casino": [t, s, "static/chunks/pages/report-daily/daily-casino-2465bb5211fcf8e2.js"],
        "/report-daily-lt/[type_huay]": [t, s, e, "static/chunks/pages/report-daily-lt/[type_huay]-95da64ec2d232474.js"],
        "/report-daily-lt/[type_huay]/[sub_type_huay]": [t, s, e, "static/chunks/pages/report-daily-lt/[type_huay]/[sub_type_huay]-53359821f22af1db.js"],
        "/report-register": [t, s, "static/chunks/pages/report-register-58d6900f3950c596.js"],
        "/report-request-otp": [t, s, "static/chunks/pages/report-request-otp-8002c9f37961a2a4.js"],
        "/request-credit": [t, s, "static/chunks/pages/request-credit-147357573b4be292.js"],
        "/request-credit/deposit": [t, s, "static/chunks/pages/request-credit/deposit-3842acaff17c5d7b.js"],
        "/sb-aq1/aq1-commission": [t, s, "static/chunks/pages/sb-aq1/aq1-commission-cd35676e766e9b2f.js"],
        "/sb-aq1/aq1-setting": [t, s, "static/chunks/pages/sb-aq1/aq1-setting-d69510ac27bac996.js"],
        "/sb-aq1/[type]": [t, s, "static/chunks/pages/sb-aq1/[type]-9fd84500059cdcb1.js"],
        "/sb-bitpayz/bitpayz-commission": [t, s, "static/chunks/pages/sb-bitpayz/bitpayz-commission-3ec6e47ce63779db.js"],
        "/sb-bitpayz/bitpayz-setting": [t, s, "static/chunks/pages/sb-bitpayz/bitpayz-setting-a8c29eeeeaf63936.js"],
        "/sb-bitpayz/[type]": [t, s, "static/chunks/pages/sb-bitpayz/[type]-3696107040cd84ad.js"],
        "/sb-p2p10x/p2p10x-commission": [t, s, "static/chunks/pages/sb-p2p10x/p2p10x-commission-606c04d62cc7adfe.js"],
        "/sb-p2p10x/p2p10x-commission-master": [t, s, "static/chunks/pages/sb-p2p10x/p2p10x-commission-master-61d27d367de84dd0.js"],
        "/sb-p2p10x/p2p10x-setting": [t, s, "static/chunks/pages/sb-p2p10x/p2p10x-setting-3d6a7f6f91400188.js"],
        "/sb-p2p10x/p2p10x-summary": [t, s, "static/chunks/pages/sb-p2p10x/p2p10x-summary-06c2933771891077.js"],
        "/sb-plz/plz-commission": [t, s, "static/chunks/pages/sb-plz/plz-commission-0c9e16a44f8fcda4.js"],
        "/sb-plz/plz-setting": [t, s, "static/chunks/pages/sb-plz/plz-setting-a44d116835df1f16.js"],
        "/sb-plz/[type]": [t, s, "static/chunks/pages/sb-plz/[type]-fbffa89d2bed81d9.js"],
        "/sb-zaap/zaap-commission": [t, s, "static/chunks/pages/sb-zaap/zaap-commission-a6bae3aee01d39f4.js"],
        "/sb-zaap/zaap-setting": [t, s, "static/chunks/pages/sb-zaap/zaap-setting-1a6b86f01a88a469.js"],
        "/sb-zaap/[type]": [t, s, "static/chunks/pages/sb-zaap/[type]-a834b604a05ae7de.js"],
        "/setting-crypto/bookbank-crypto": [t, s, "static/chunks/pages/setting-crypto/bookbank-crypto-af1379bf2fbf91f1.js"],
        "/setting-crypto/setting-common-crypto": [t, s, "static/chunks/pages/setting-crypto/setting-common-crypto-f363fe6fc780c431.js"],
        "/setting-crypto/setting-crypto-exchange": [t, s, "static/chunks/pages/setting-crypto/setting-crypto-exchange-452d71fe9ae7a9b7.js"],
        "/setting-deposit-withdraw": [t, s, a, n, i, g, y, b, h, l, c, o, r, k, f, j, w, "static/chunks/pages/setting-deposit-withdraw-fa09a104802f468a.js"],
        "/setting-deposit-withdraw/deposit-withdraw-aq1": [t, s, a, n, i, g, y, b, h, l, c, o, r, k, f, j, w, "static/chunks/pages/setting-deposit-withdraw/deposit-withdraw-aq1-e4eca5c2905c1006.js"],
        "/setting-deposit-withdraw/deposit-withdraw-bookbank": [t, s, a, n, i, g, y, b, h, l, c, o, r, k, f, j, w, "static/chunks/pages/setting-deposit-withdraw/deposit-withdraw-bookbank-d1912aaca358b837.js"],
        "/setting-deposit-withdraw/deposit-withdraw-crypto": [t, s, a, n, i, g, y, b, h, l, c, o, r, k, f, j, w, "static/chunks/pages/setting-deposit-withdraw/deposit-withdraw-crypto-4046a8f4c6cd3f36.js"],
        "/setting-deposit-withdraw/deposit-withdraw-p2p": [t, s, a, n, i, g, y, b, h, l, c, o, r, k, f, j, w, "static/chunks/pages/setting-deposit-withdraw/deposit-withdraw-p2p-42d62e4cfe2626fb.js"],
        "/setting-deposit-withdraw-aq1": [t, s, "static/chunks/pages/setting-deposit-withdraw-aq1-7835cb62ef92677c.js"],
        "/setting-deposit-withdraw-bitpayz": [t, s, "static/chunks/pages/setting-deposit-withdraw-bitpayz-e36b1915cd7c3565.js"],
        "/setting-deposit-withdraw-p2p": [t, s, "static/chunks/pages/setting-deposit-withdraw-p2p-ccccd3f80f8e4fa1.js"],
        "/setting-deposit-withdraw-plz": [t, s, "static/chunks/pages/setting-deposit-withdraw-plz-b0ef347362d06556.js"],
        "/setting-deposit-withdraw-zaap": [t, s, "static/chunks/pages/setting-deposit-withdraw-zaap-c62e29d30bdb4ab1.js"],
        "/setting-domain": [t, s, "static/chunks/pages/setting-domain-d81c7296a9053593.js"],
        "/share-af/setting-share-af": [t, s, "static/chunks/pages/share-af/setting-share-af-405ac409bbd8a3b6.js"],
        "/share-af/share-af-list": [t, s, "static/chunks/pages/share-af/share-af-list-15f18b2ffe42769d.js"],
        "/summary-deposit-withdraw/agent-master": [t, s, "static/chunks/pages/summary-deposit-withdraw/agent-master-295e5243f4e01e3c.js"],
        "/summary-deposit-withdraw/master-system": [t, s, "static/chunks/pages/summary-deposit-withdraw/master-system-dd0ec46f9402259d.js"],
        "/summary-game/summary-game-by-date": [t, s, "static/chunks/pages/summary-game/summary-game-by-date-71006c4829282c96.js"],
        "/summary-game/summary-game-by-month": [t, s, "static/chunks/pages/summary-game/summary-game-by-month-01e04af496b73225.js"],
        "/system-affiliate/setting-commission-affiliate": [t, s, "static/chunks/pages/system-affiliate/setting-commission-affiliate-a611b62f7dd0b4a3.js"],
        "/system-affiliate/setting-commission-affiliate-casino": [t, s, "static/chunks/pages/system-affiliate/setting-commission-affiliate-casino-934dd388c2130049.js"],
        "/system-affiliate/setting-message-affiliate": [t, s, "static/chunks/pages/system-affiliate/setting-message-affiliate-5bdb28255eeb294a.js"],
        "/system-affiliate/setting-message-affiliate-casino": [t, s, "static/chunks/pages/system-affiliate/setting-message-affiliate-casino-fcd247ac1a62c55a.js"],
        "/system-member": [t, s, "static/chunks/pages/system-member-f426447a95cdf41a.js"],
        "/system-setting/banner-casino": [t, s, "static/chunks/pages/system-setting/banner-casino-a1c443f6797208ce.js"],
        "/system-setting/execute-job": [t, s, "static/chunks/pages/system-setting/execute-job-8721ac7e565a5200.js"],
        "/system-setting/gen-lt-stock": [t, s, "static/chunks/pages/system-setting/gen-lt-stock-c54467dce6d2b302.js"],
        "/system-setting/report-outstanding": [t, s, "static/chunks/pages/system-setting/report-outstanding-bb6a3c8b6b59edea.js"],
        "/system-setting/setting-bet/[sub_type_huay]": [t, s, e, "static/chunks/pages/system-setting/setting-bet/[sub_type_huay]-6195800214b67a0f.js"],
        "/system-setting/setting-bet-casino": [t, s, "static/chunks/pages/system-setting/setting-bet-casino-c176103c98d9d28f.js"],
        "/system-setting/setting-channel-ref": [t, s, "static/chunks/pages/system-setting/setting-channel-ref-aa6a2316c675b9fe.js"],
        "/system-setting/setting-channel-ref-agent": [t, s, "static/chunks/pages/system-setting/setting-channel-ref-agent-6cd9a973b3d50aa4.js"],
        "/system-setting/setting-domain-agent": [t, s, "static/chunks/pages/system-setting/setting-domain-agent-7db5faffa567a27b.js"],
        "/system-setting/setting-expenses": [t, s, "static/chunks/pages/system-setting/setting-expenses-324001245efe7b58.js"],
        "/system-setting/setting-expire": [t, s, "static/chunks/pages/system-setting/setting-expire-b8f6192733da4793.js"],
        "/system-setting/setting-game": [t, s, "static/chunks/pages/system-setting/setting-game-2fe80ef5a1fd1719.js"],
        "/system-setting/setting-message-provider": [t, s, "static/chunks/pages/system-setting/setting-message-provider-72628fa25ebc1880.js"],
        "/system-setting/setting-number/[sub_type_huay]": [t, s, "static/chunks/pages/system-setting/setting-number/[sub_type_huay]-d913d23b2da838d1.js"],
        "/system-setting/setting-only-agent": [t, s, "static/chunks/pages/system-setting/setting-only-agent-5b38ffec7d6fbc17.js"],
        "/system-setting/setting-open-casino": [t, s, "static/chunks/pages/system-setting/setting-open-casino-c977955bd6364413.js"],
        "/system-setting/setting-open-lotto": [t, s, "static/chunks/pages/system-setting/setting-open-lotto-438d6dc3517911d1.js"],
        "/system-setting/setting-open-lt": [t, s, "static/chunks/pages/system-setting/setting-open-lt-fb9e8f8fca6d7853.js"],
        "/system-setting/setting-opening": [t, s, "static/chunks/pages/system-setting/setting-opening-581d2cf2d1ab36b3.js"],
        "/system-setting/setting-random": [t, s, "static/chunks/pages/system-setting/setting-random-1ef08a7a5cdf676a.js"],
        "/system-setting/setting-ref-domain": [t, s, "static/chunks/pages/system-setting/setting-ref-domain-045a12089d289e9f.js"],
        "/system-setting/setting-register": [t, s, "static/chunks/pages/system-setting/setting-register-ec2b242e47974331.js"],
        "/system-setting/setting-rule": [t, s, "static/chunks/pages/system-setting/setting-rule-aa2d02819b7eb508.js"],
        "/system-setting/setting-shooting-reward-price": [t, s, "static/chunks/pages/system-setting/setting-shooting-reward-price-349148f509cee247.js"],
        "/system-setting/setting-sms-message": [t, s, "static/chunks/pages/system-setting/setting-sms-message-8bc2c9128bf58948.js"],
        "/system-setting/setting-turnover": [t, s, "static/chunks/pages/system-setting/setting-turnover-1eedfca7e80c6ce8.js"],
        "/system-setting/setting-web": [t, s, "static/chunks/pages/system-setting/setting-web-18c7d1e14398857b.js"],
        "/system-setting/sync-report-credit": [t, s, "static/chunks/pages/system-setting/sync-report-credit-2c42ba380360aff6.js"],
        "/system-setting-register": [t, s, "static/chunks/pages/system-setting-register-ee2193eebadcd9b8.js"],
        "/system-user-agent": [t, s, "static/chunks/pages/system-user-agent-769dea056a5b9b41.js"],
        "/system-user-agent/commission/[id]": [t, s, "static/chunks/pages/system-user-agent/commission/[id]-f231a45445777b5f.js"],
        "/system-user-agent/create": [t, s, "static/chunks/pages/system-user-agent/create-2c2c7d967e25fb57.js"],
        "/system-user-agent/credit/[id]": [t, s, "static/chunks/pages/system-user-agent/credit/[id]-4152a3d9de431e30.js"],
        "/system-user-agent/log-history/[id]": [t, s, "static/chunks/pages/system-user-agent/log-history/[id]-d57dc9e0586fb140.js"],
        "/system-user-agent/member-info/[id]": [t, s, "static/chunks/pages/system-user-agent/member-info/[id]-005bfa3bfb3673ed.js"],
        "/system-user-agent/setting-commission/[id]": [t, s, "static/chunks/pages/system-user-agent/setting-commission/[id]-0994460300796031.js"],
        "/system-user-agent/[id]": [t, s, "static/chunks/pages/system-user-agent/[id]-62042c59a208b8c2.js"],
        "/system-user-assistant": [t, s, "static/chunks/pages/system-user-assistant-2abef28a56f2b797.js"],
        "/system-user-assistant/create": [t, s, "static/chunks/pages/system-user-assistant/create-af2f3cee7b7d9b7a.js"],
        "/system-user-assistant/detail/[id]": [t, s, "static/chunks/pages/system-user-assistant/detail/[id]-5823a2ae1e1e2779.js"],
        "/system-user-assistant/log-history/[id]": [t, s, "static/chunks/pages/system-user-assistant/log-history/[id]-9c37a090962ebdda.js"],
        "/system-user-assistant/[id]": [t, s, "static/chunks/pages/system-user-assistant/[id]-af9309bb56eee8c6.js"],
        "/system-user-master": [t, s, "static/chunks/pages/system-user-master-f097bb0d20acadc6.js"],
        "/system-user-master/commission/[id]": [t, s, "static/chunks/pages/system-user-master/commission/[id]-3530137c4041241d.js"],
        "/system-user-master/create": [t, s, "static/chunks/pages/system-user-master/create-cc8b9e9ee2c565fd.js"],
        "/system-user-master/credit/[id]": [t, s, "static/chunks/pages/system-user-master/credit/[id]-0043c8eddd5cb8e0.js"],
        "/system-user-master/log-history/[id]": [t, s, "static/chunks/pages/system-user-master/log-history/[id]-bb329653564d2ebf.js"],
        "/system-user-master/member-info/[id]": [t, s, "static/chunks/pages/system-user-master/member-info/[id]-445ef01b15ff9b67.js"],
        "/system-user-master/[id]": [t, s, "static/chunks/pages/system-user-master/[id]-f7cdb012527a82a3.js"],
        "/ticket-aq": [t, s, "static/chunks/pages/ticket-aq-3f4ca8771914a80c.js"],
        "/ticket-aq/comment/[id]": [t, s, "static/chunks/pages/ticket-aq/comment/[id]-ee7f0d36b214bd56.js"],
        "/user-manual/[type]": [t, s, "static/chunks/pages/user-manual/[type]-f99126f033fe5e51.js"],
        "/vip-deposit-setting": [t, s, "static/chunks/pages/vip-deposit-setting-174cba1eb525384a.js"],
        "/vip-setting": [t, s, "static/chunks/pages/vip-setting-8da4fb47830c7177.js"],
        "/withdraw-agent": [p, t, s, a, n, i, c, o, r, m, u, d, "static/chunks/pages/withdraw-agent-2d930353fb942d4c.js"],
        "/withdraw-master": [p, t, s, a, n, i, c, o, r, m, u, d, "static/chunks/pages/withdraw-master-03c3e8a985af5896.js"],
        sortedPages: ["/", "/404", "/_app", "/_error", "/banner", "/bet-lt/[type_huay]", "/bet-lt/[type_huay]/[sub_type_huay]", "/bet-lt-conqueror/[type_huay]", "/bet-lt-conqueror/[type_huay]/[sub_type_huay]", "/betting-list", "/birthday-promotion/add", "/birthday-promotion/list", "/birthday-promotion/setting", "/birthday-promotion/view", "/book-bank", "/book-bank/create", "/book-bank/lock-bank-info/[id]", "/book-bank/[id]", "/book-bank-special/[bank_code]", "/book-bank-special/[bank_code]/create", "/book-bank-special/[bank_code]/[id]", "/casino-game", "/change-password", "/commission/commission-game", "/commission/commission-month", "/commission/commission-month-casino", "/commission/commission-weekly", "/commission/commission-weekly-casino", "/commission/setting-game-casino", "/commission-lottery/commission-lottery-month", "/commission-lottery/commission-lottery-year", "/contact", "/contact-agent", "/crypto/commission-crypto", "/crypto/commission-crypto-admin", "/crypto/commission-crypto-master", "/crypto/setting-commission-crypto", "/crypto-wallet/own-wallet", "/crypto-wallet/own-wallet/wallet-crypto-trx", "/crypto-wallet/settlement-wallet-crypto", "/dashboard", "/dashboard-game", "/dashboard-system", "/deposit-withdraw/all", "/deposit-withdraw/pending", "/direct-deposit-withdraw", "/home", "/login", "/lotto-huay/[type_huay]", "/lotto-huay/[type_huay]/bet-setting", "/lotto-huay/[type_huay]/dashboard", "/lotto-huay/[type_huay]/enable-setting", "/lotto-huay/[type_huay]/payment-rate-setting", "/lotto-huay/[type_huay]/price-setting", "/lotto-huay/[type_huay]/schedule-setting", "/lotto-huay/[type_huay]/thrust-round", "/lotto-huay/[type_huay]/[sub_type_huay]", "/lotto-huay/[type_huay]/[sub_type_huay]/bet-setting", "/lotto-huay/[type_huay]/[sub_type_huay]/dashboard", "/lotto-huay/[type_huay]/[sub_type_huay]/enable-setting", "/lotto-huay/[type_huay]/[sub_type_huay]/payment-rate-setting", "/lotto-huay/[type_huay]/[sub_type_huay]/schedule-setting", "/lotto-huay/[type_huay]/[sub_type_huay]/thrust-round", "/lucky-draw-banner", "/lucky-draw-join-round", "/lucky-draw-level", "/lucky-draw-level/setting", "/lucky-draw-prizes", "/lucky-draw-prizes/detail/[id]", "/lucky-draw-setting-round", "/lucky-draw-setting-round/invite", "/lucky-draw-setting-round/setting", "/lucky-draw-setting-round/setting-reward/[id]", "/member", "/member/bet/[id]", "/member/book-bank/[id]", "/member/create", "/member/credit/[id]", "/member/huay-transaction/[id]", "/member/log-history/[id]", "/member/lucky-draw/[id]", "/member/member-info/[id]", "/member/[id]", "/message-in", "/message-out", "/mini-games-hilo", "/mini-games-huakoi", "/mini-games-paoyingchub", "/mini-games-setting/[mini_game]", "/monitoring", "/monitoring/create", "/monitoring/[id]", "/new-member-promotion/list-new-member", "/new-member-promotion/setting-new-member", "/promotion", "/promotion/create", "/promotion/[id]", "/promotion-direct-deposit/report", "/promotion-direct-deposit/summary", "/promotion-topup-direct-deposit/report", "/promotion-topup-direct-deposit/summary", "/promotion-user-list", "/promotion-user-list/create", "/promotion-user-list/update/[id]", "/promotion-user-list/view/[id]", "/public-relations-announcement", "/public-relations-announcement/form", "/public-relations-announcement/[id]", "/public-relations-marquee", "/public-relations-news-popup", "/public-relations-news-popup/create", "/public-relations-news-popup/[id]", "/public-relations-news-popup-casino", "/public-relations-news-popup-casino/create", "/public-relations-news-popup-casino/[id]", "/report-account-summary/calendar", "/report-account-summary/retrospect", "/report-account-summary/today", "/report-balance-bof", "/report-credit-transaction/credit-transaction-agent", "/report-credit-transaction/credit-transaction-agent-by-master", "/report-credit-transaction/credit-transaction-all", "/report-credit-transaction/credit-transaction-master", "/report-credit-transaction/credit-transaction-member", "/report-daily/daily-all", "/report-daily/daily-casino", "/report-daily-lt/[type_huay]", "/report-daily-lt/[type_huay]/[sub_type_huay]", "/report-register", "/report-request-otp", "/request-credit", "/request-credit/deposit", "/sb-aq1/aq1-commission", "/sb-aq1/aq1-setting", "/sb-aq1/[type]", "/sb-bitpayz/bitpayz-commission", "/sb-bitpayz/bitpayz-setting", "/sb-bitpayz/[type]", "/sb-p2p10x/p2p10x-commission", "/sb-p2p10x/p2p10x-commission-master", "/sb-p2p10x/p2p10x-setting", "/sb-p2p10x/p2p10x-summary", "/sb-plz/plz-commission", "/sb-plz/plz-setting", "/sb-plz/[type]", "/sb-zaap/zaap-commission", "/sb-zaap/zaap-setting", "/sb-zaap/[type]", "/setting-crypto/bookbank-crypto", "/setting-crypto/setting-common-crypto", "/setting-crypto/setting-crypto-exchange", "/setting-deposit-withdraw", "/setting-deposit-withdraw/deposit-withdraw-aq1", "/setting-deposit-withdraw/deposit-withdraw-bookbank", "/setting-deposit-withdraw/deposit-withdraw-crypto", "/setting-deposit-withdraw/deposit-withdraw-p2p", "/setting-deposit-withdraw-aq1", "/setting-deposit-withdraw-bitpayz", "/setting-deposit-withdraw-p2p", "/setting-deposit-withdraw-plz", "/setting-deposit-withdraw-zaap", "/setting-domain", "/share-af/setting-share-af", "/share-af/share-af-list", "/summary-deposit-withdraw/agent-master", "/summary-deposit-withdraw/master-system", "/summary-game/summary-game-by-date", "/summary-game/summary-game-by-month", "/system-affiliate/setting-commission-affiliate", "/system-affiliate/setting-commission-affiliate-casino", "/system-affiliate/setting-message-affiliate", "/system-affiliate/setting-message-affiliate-casino", "/system-member", "/system-setting/banner-casino", "/system-setting/execute-job", "/system-setting/gen-lt-stock", "/system-setting/report-outstanding", "/system-setting/setting-bet/[sub_type_huay]", "/system-setting/setting-bet-casino", "/system-setting/setting-channel-ref", "/system-setting/setting-channel-ref-agent", "/system-setting/setting-domain-agent", "/system-setting/setting-expenses", "/system-setting/setting-expire", "/system-setting/setting-game", "/system-setting/setting-message-provider", "/system-setting/setting-number/[sub_type_huay]", "/system-setting/setting-only-agent", "/system-setting/setting-open-casino", "/system-setting/setting-open-lotto", "/system-setting/setting-open-lt", "/system-setting/setting-opening", "/system-setting/setting-random", "/system-setting/setting-ref-domain", "/system-setting/setting-register", "/system-setting/setting-rule", "/system-setting/setting-shooting-reward-price", "/system-setting/setting-sms-message", "/system-setting/setting-turnover", "/system-setting/setting-web", "/system-setting/sync-report-credit", "/system-setting-register", "/system-user-agent", "/system-user-agent/commission/[id]", "/system-user-agent/create", "/system-user-agent/credit/[id]", "/system-user-agent/log-history/[id]", "/system-user-agent/member-info/[id]", "/system-user-agent/setting-commission/[id]", "/system-user-agent/[id]", "/system-user-assistant", "/system-user-assistant/create", "/system-user-assistant/detail/[id]", "/system-user-assistant/log-history/[id]", "/system-user-assistant/[id]", "/system-user-master", "/system-user-master/commission/[id]", "/system-user-master/create", "/system-user-master/credit/[id]", "/system-user-master/log-history/[id]", "/system-user-master/member-info/[id]", "/system-user-master/[id]", "/ticket-aq", "/ticket-aq/comment/[id]", "/user-manual/[type]", "/vip-deposit-setting", "/vip-setting", "/withdraw-agent", "/withdraw-master"]
    }
}("static/chunks/53440-0163837175bf2211.js", "static/chunks/11382-e0587a4d9f11bda3.js", "static/chunks/43792-6beb280abee52d20.js", "static/chunks/4585-8ca8453888a35b6b.js", "static/chunks/71577-2a1d4b483aecd54b.js", "static/chunks/58278-186a2fe88259535a.js", "static/chunks/26574-1d35d529c5620651.js", "static/chunks/76519-2b79293c5bbe63e8.js", "static/chunks/82071-d53a62644d9e521c.js", "static/chunks/29107295-f5d3d9a71e7e292a.js", "static/chunks/81758-fb1770cc35b5017e.js", "static/chunks/32013-0581131e478110d4.js", "static/chunks/26131-7181c0ed7df012e1.js", "static/chunks/23530-73d6d155b2e1908a.js", "static/chunks/80173-cb43808828cf8cd4.js", "static/chunks/27074-49551d25206a6571.js", "static/chunks/73553-e06b0b51d8df03a2.js", "static/chunks/10957-ec0c66c30835c7c7.js", "static/chunks/79915-625d05a6d8babafc.js", "static/chunks/64674-ff9880e5c8270883.js", "static/chunks/63913-b45f49e797ea2684.js", "static/chunks/87019-4448dc0e8a79bbd9.js"), self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();